# Generated by Django 4.2.11 on 2024-05-11 10:42

import boots.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Boots",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("blue", "Blue"),
                            ("green", "Green"),
                            ("black", "Black"),
                            ("white", "White"),
                            ("yellow", "Yellow"),
                            ("purple", "Purple"),
                            ("orange", "Orange"),
                            ("another", "Another"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("adidas", "Adidas"),
                            ("nike", "Nike"),
                            ("puma", "Puma"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(upload_to=boots.models.boots_custom_path),
                ),
                ("new", models.BooleanField(default=True)),
                ("popular", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Size",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "size",
                    models.PositiveIntegerField(
                        help_text="Choose a size between 35 and 45",
                        validators=[
                            django.core.validators.MinValueValidator(35),
                            django.core.validators.MaxValueValidator(45),
                        ],
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        help_text="Stock available for this size"
                    ),
                ),
                (
                    "boots",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sizes",
                        to="boots.boots",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BootsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to=boots.models.boots_custom_path)),
                (
                    "boots",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="boots.boots",
                    ),
                ),
            ],
        ),
    ]
