# Generated by Django 4.2.11 on 2024-06-20 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boots",
            name="type",
            field=models.CharField(
                choices=[("сороконіжки", "Сороконіжки"), ("бутси", "Бутси")],
                default="сороконіжки",
                max_length=100,
            ),
        ),
    ]
