# Generated by Django 4.2.11 on 2024-04-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boots",
            name="new",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="boots",
            name="popular",
            field=models.BooleanField(default=False),
        ),
    ]
