# Generated by Django 4.2.11 on 2024-03-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_remove_order_products_order_boots_and_more'),
        ('boots', '0002_boots'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
