# Generated by Django 4.2.11 on 2024-03-04 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0003_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boots',
            name='size',
            field=models.PositiveIntegerField(help_text='Choose a size between 35 and 45', validators=[django.core.validators.MinValueValidator(35), django.core.validators.MaxValueValidator(45)]),
        ),
    ]
