# Generated by Django 4.2.11 on 2024-03-04 14:03

import boots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0004_alter_boots_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boots',
            name='image',
            field=models.ImageField(upload_to=boots.models.boots_custom_path),
        ),
    ]
