# Generated by Django 4.2.11 on 2024-03-04 14:35

import boots.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boots', '0005_alter_boots_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=boots.models.boots_custom_path)),
                ('boots', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='boots.boots')),
            ],
        ),
    ]
