# Generated by Django 4.2.11 on 2024-06-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="boots",
        ),
    ]
