# Generated by Django 4.2.11 on 2025-01-29 12:30

import accessories.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('main_image', models.ImageField(upload_to=accessories.models.accessory_custom_path)),
                ('type', models.CharField(choices=[('баф', 'Баф'), ('шкарпетки', 'Шкарпетки'), ('гетри-обрізки', 'Гетри-обрізки'), ('щитки', 'Щитки'), ('рукавички', 'Рукавички'), ('мішечки', 'Мішечки')], max_length=255)),
            ],
        ),
    ]
