# Generated by Django 4.2.11 on 2025-02-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
