# Generated by Django 4.2.11 on 2024-04-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("boots", "0001_initial"),
        ("cart", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                related_name="boots", through="cart.CartProduct", to="boots.boots"
            ),
        ),
    ]
