# Generated by Django 4.2.11 on 2024-06-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_cartproduct_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartproduct",
            name="size",
            field=models.PositiveIntegerField(),
        ),
    ]
