# Generated by Django 4.2.11 on 2024-04-14 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cart", "0003_alter_cart_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone_number", models.IntegerField()),
                ("email", models.EmailField(max_length=254)),
                ("region", models.CharField(max_length=255)),
                ("city_town", models.CharField(max_length=255)),
                ("post_office_number", models.IntegerField()),
                (
                    "delivery_method",
                    models.CharField(
                        choices=[
                            ("self-delivery", "Самовивіз"),
                            ("delivery-man", "Кур'єр"),
                        ],
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cart",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cart.cart"
                    ),
                ),
            ],
        ),
    ]
