# Generated by Django 4.2.11 on 2024-08-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_total_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="delivery_method",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="Оплатити при отриманні", max_length=255),
        ),
        migrations.AlterField(
            model_name="order",
            name="post_office_number",
            field=models.CharField(max_length=255),
        ),
    ]
