# Generated by Django 4.2.11 on 2024-08-08 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_remove_order_delivery_method_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(max_length=255),
        ),
    ]
